# Generated by Django 5.2 on 2026-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicwebhook",
            name="request_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
