# Generated by Django 5.1.4 on 2025-05-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SistemaMedicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("A", "Fase A"),
                            ("B", "Fase B"),
                            ("C", "Fase C"),
                            ("N", "Fase N"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "Sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="endpoint.sistemamedicion",
                    ),
                ),
            ],
            options={
                "unique_together": {("Sistema", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Lecturas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo", models.DateTimeField(db_index=True)),
                ("voltaje", models.FloatField()),
                ("corriente", models.FloatField()),
                ("angulo", models.FloatField()),
                ("kwh", models.FloatField(blank=True, null=True)),
                (
                    "fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Lecturas",
                        to="endpoint.fase",
                    ),
                ),
            ],
            options={
                "ordering": ["-tiempo"],
                "indexes": [
                    models.Index(
                        fields=["fase", "tiempo"], name="endpoint_le_fase_id_6024a7_idx"
                    )
                ],
            },
        ),
    ]
