# Generated by Django 5.1.4 on 2025-05-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoint", "0002_rename_description_sistemamedicion_descripcion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sistemamedicion",
            old_name="latitude",
            new_name="latitud",
        ),
        migrations.RenameField(
            model_name="sistemamedicion",
            old_name="longitude",
            new_name="longitud",
        ),
    ]
