# Generated by Django 5.1.4 on 2026-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoint", "0003_rename_latitude_sistemamedicion_latitud_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturas",
            name="kw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sistemamedicion",
            name="qr",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="lecturas",
            name="angulo",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecturas",
            name="corriente",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecturas",
            name="voltaje",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
